# Generated by Django 3.1.5 on 2021-01-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=13, null=True)),
                ('notes', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
